const constants = {
  REQUEST_DATA: 'REQUEST_DATA',
  FETCH_ERROR: 'FETCH_ERROR',
  IS_FETCHING: 'IS_FETCHING',
  INPUT_ERROR: 'INPUT_ERROR',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  SUBMIT_TYPE: 'SUBMIT_TYPE',
  SET_BACKGROUND: 'SET_BACKGROUND',
  SET_ARTIST_TRACK_INFO : 'SET_ARTIST_TRACK_INFO',
  requestService: {
    YOUTUBE: 'YOUTUBE',
    SPOTIFY: 'SPOTIFY',
    DEEZER: 'DEEZER',
    YOUTUBE_MUSIC: 'YOUTUBE_MUSIC',
    APPLE_MUSIC: 'APPLE_MUSIC',
  },
  requestType: {
    TRACK: 'TRACK',
    SEARCH: 'SEARCH',
  },
  SUBMIT_FORM: 'SUBMIT_FORM',
  submitTypes: {
    BY_URL: 'BY_URL',
    BY_ARTIST_TRACK: 'BY_ARTIST_TRACK',
  },
};

export default constants;
